# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1649183362165055183f3f6efc57a585b3456e4eab14c6a7d959ceb78f1c93f4ac21fefe621478ef63d85f4c842c211de8b956c9c033935382aceb65189a54fd

test:
  secret_key_base: fc2652a537845c0a899d36def034ab3e662976e6594f39bce5fd69e518433b099b0e7748fb5d9618f81e3db32131afddb2521a207a4b8847f96791292e6a7df7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
